window.GRAPH_DATA = {
  site: {
    title: "Graph Parameter Hierarchy",
    homepageUrl: "https://yeonsuchang.com",
    homepageLabel: "Homepage",
    panelTitle: "All nodes",
    highlightLabel: "k-hierarchy",
    filterPlaceholder: "Filter...",
    analyticsId: "G-Z5D0WM7N9S"
  },
  settings: {
    layout: {
      nodeSep: 54,
      rankSep: 120,
      edgeSep: 34
    },
    equivalentAliases: {
      "rank-width": "clique-width",
      "linear NLC-width": "linear clique-width",
      "component twin-width": "clique-width",
      "NLC-width": "clique-width",
      "boolean-width": "clique-width",
      "∞-flip-width": "clique-width",
      "total twin-width": "linear rank-width",
      "edge-crossing width": "tree-partition-width",
      "queue number": "track number",
      "interval number": "track number",
      "arboricity": "degeneracy",
      "rank-depth": "shrub-depth",
      "branch-depth": "tree-depth",
      "weak ∞-coloring number": "tree-depth",
      "strong ∞-coloring number": "tree-width",
      "branch-width": "tree-width",
      "tangle number": "tree-width",
      "bramble number": "tree-width",
      "separation number": "tree-width",
      "linkedness": "tree-width",
      "well-linked number": "tree-width",
      "fractional Hadwiger number": "tree-width",
      "maximum matching": "vertex cover number"
    },
    preferredAnchors: [
      "clique-width",
      "linear clique-width",
      "tree-width",
      "tree-depth",
      "track number",
      "vertex cover number",
      "degeneracy",
      "shrub-depth",
      "tree-partition-width",
      "linear rank-width",
      "component twin-width",
      "NLC-width",
      "boolean-width",
      "∞-flip-width",
      "total twin-width",
      "edge-crossing width",
      "queue number",
      "interval number",
      "arboricity",
      "rank-depth",
      "branch-depth",
      "weak ∞-coloring number",
      "strong ∞-coloring number",
      "branch-width",
      "tangle number",
      "bramble number",
      "separation number",
      "linkedness",
      "well-linked number",
      "fractional Hadwiger number",
      "maximum matching"
    ]
  },
  graph: {
    edges: [
      { source: "acyclic chromatic number", target: "boxicity" },
      { source: "acyclic chromatic number", target: "degeneracy" },
      { source: "average degree", target: "minimum degree" },
      { source: "average distance", target: "girth" },
      { source: "bandwidth", target: "bisection width" },
      { source: "bandwidth", target: "cut-width" },
      { source: "bandwidth", target: "track number" },
      { source: "bisection width", target: "distance to Disconnected" },
      { source: "boxicity", target: "chordality" },
      { source: "burning number", target: "max diameter of components" },
      { source: "carving-width", target: "maximum degree" },
      { source: "carving-width", target: "slim tree-cut width" },
      { source: "carving-width", target: "tree-cut width" },
      { source: "chromatic number", target: "chordality" },
      { source: "chromatic number", target: "cochromatic number" },
      { source: "chromatic number", target: "maximum clique" },
      { source: "clique cover number", target: "cochromatic number" },
      { source: "clique cover number", target: "maximum independent set" },
      { source: "clique-width", target: "boolean-width", type: "equivalent" },
      { source: "clique-width", target: "component twin-width", type: "equivalent" },
      { source: "clique-width", target: "mim-width" },
      { source: "clique-width", target: "NLC-width", type: "equivalent" },
      { source: "clique-width", target: "rank-width", type: "equivalent" },
      { source: "clique-width", target: "stretch-width" },
      { source: "clique-width", target: "∞-flip-width", type: "equivalent" },
      { source: "crossing number", target: "genus" },
      { source: "cut-width", target: "carving-width" },
      { source: "cut-width", target: "path-width" },
      { source: "cycle rank", target: "directed path-width" },
      { source: "cycle rank", target: "weak (∞, →)-coloring number", type: "equivalent" },
      { source: "DAG-depth", target: "cycle rank" },
      { source: "DAG-width", target: "directed tree-width" },
      { source: "degeneracy", target: "arboricity", type: "equivalent" },
      { source: "degeneracy", target: "average degree" },
      { source: "degeneracy", target: "chromatic number" },
      { source: "directed path-width", target: "Kelly-width" },
      { source: "distance to Bipartite", target: "chromatic number" },
      { source: "distance to Bipartite", target: "distance to Perfect" },
      { source: "distance to Chordal", target: "chordality" },
      { source: "distance to Chordal", target: "distance to Perfect" },
      { source: "distance to Clique", target: "clique cover number" },
      { source: "distance to Clique", target: "distance to Cluster" },
      { source: "distance to Clique", target: "distance to Co-Cluster" },
      { source: "distance to Clique", target: "edge clique cover number" },
      { source: "distance to Cluster", target: "distance to Block" },
      { source: "distance to Cluster", target: "distance to Cograph" },
      { source: "distance to Cluster", target: "distance to Interval" },
      { source: "distance to Co-Cluster", target: "distance to Cograph" },
      { source: "distance to Cograph", target: "chordality" },
      { source: "distance to Cograph", target: "clique-width" },
      { source: "distance to Cograph", target: "diameter" },
      { source: "distance to Cograph", target: "distance to Perfect" },
      { source: "distance to Cograph", target: "max diameter of components" },
      { source: "distance to disjoint Paths", target: "distance to Interval" },
      { source: "distance to disjoint Paths", target: "feedback vertex set number" },
      { source: "distance to disjoint Paths", target: "path-width" },
      { source: "distance to disjoint Paths", target: "ℎ-index" },
      { source: "distance to Interval", target: "distance to Chordal" },
      { source: "distance to Linear forest", target: "distance to Block" },
      { source: "distance to Linear forest", target: "feedback vertex set number" },
      { source: "distance to Linear forest", target: "path-width" },
      { source: "distance to Outerplanar", target: "distance to Planar" },
      { source: "distance to Outerplanar", target: "tree-width" },
      { source: "distance to Planar", target: "acyclic chromatic number" },
      { source: "distance to Planar", target: "twin-width" },
      { source: "domination number", target: "diameter" },
      { source: "domination number", target: "max diameter of components" },
      { source: "edge clique cover number", target: "neighborhood diversity" },
      { source: "edge clique cover number", target: "simultaneous interval number" },
      { source: "edge-cut width", target: "slim tree-cut width" },
      { source: "feedback edge set number", target: "edge-cut width" },
      { source: "feedback edge set number", target: "feedback vertex set number" },
      { source: "feedback edge set number", target: "genus" },
      { source: "feedback edge set number", target: "𝑐-closure" },
      { source: "feedback vertex set number", target: "distance to Bipartite" },
      { source: "feedback vertex set number", target: "distance to Chordal" },
      { source: "feedback vertex set number", target: "distance to Outerplanar" },
      { source: "genus", target: "stack number" },
      { source: "genus", target: "twin-width" },
      { source: "geometric thickness", target: "thickness" },
      { source: "Kelly-width", target: "DAG-width" },
      { source: "Kelly-width", target: "strong (∞, →)-coloring number", type: "equivalent" },
      { source: "linear clique-width", target: "clique-width" },
      { source: "linear clique-width", target: "linear NLC-width", type: "equivalent" },
      { source: "linear mim-width", target: "mim-width" },
      { source: "linear rank-width", target: "clique-width" },
      { source: "linear rank-width", target: "total twin-width", type: "equivalent" },
      { source: "max diameter of components", target: "average distance" },
      { source: "max leaf number", target: "bandwidth" },
      { source: "max leaf number", target: "distance to Linear forest" },
      { source: "max leaf number", target: "feedback edge set number" },
      { source: "maximum degree", target: "ℎ-index" },
      { source: "maximum degree", target: "𝑐-closure" },
      { source: "maximum independent set", target: "domination number" },
      { source: "maximum independent set", target: "maximum induced matching" },
      { source: "maximum induced matching", target: "diameter" },
      { source: "mim-width", target: "o-mim-width" },
      { source: "minimum degree", target: "distance to Disconnected" },
      { source: "minimum degree", target: "domatic number" },
      { source: "minor-matching hypertree-width", target: "sim-width" },
      { source: "modular-width", target: "clique-width" },
      { source: "modular-width", target: "max diameter of components" },
      { source: "neighborhood diversity", target: "modular-width" },
      { source: "o-mim-width", target: "sim-width" },
      { source: "path-independence number", target: "tree-independence number" },
      { source: "path-width", target: "linear clique-width" },
      { source: "path-width", target: "simultaneous interval number" },
      { source: "path-width", target: "tree-width" },
      { source: "reduced bandwidth", target: "reduced cut-width" },
      { source: "reduced cut-width", target: "twin-width" },
      { source: "shrub-depth", target: "linear clique-width" },
      { source: "shrub-depth", target: "rank-depth", type: "equivalent" },
      { source: "simultaneous interval number", target: "path-independence number" },
      { source: "simultaneous interval number", target: "thinness" },
      { source: "simultaneous interval number", target: "track number" },
      { source: "slim tree-cut width", target: "tree-cut width" },
      { source: "slim tree-cut width", target: "α-edge-crossing width" },
      { source: "stack number", target: "acyclic chromatic number" },
      { source: "stack number", target: "geometric thickness" },
      { source: "stretch-width", target: "reduced bandwidth" },
      { source: "thickness", target: "average degree" },
      { source: "thinness", target: "boxicity" },
      { source: "thinness", target: "linear mim-width" },
      { source: "track number", target: "acyclic chromatic number" },
      { source: "track number", target: "geometric thickness" },
      { source: "track number", target: "interval number", type: "equivalent" },
      { source: "track number", target: "queue number", type: "equivalent" },
      { source: "tree bandwidth", target: "tree-width" },
      { source: "tree-cut width", target: "tree-partition-width" },
      { source: "tree-depth", target: "branch-depth", type: "equivalent" },
      { source: "tree-depth", target: "diameter" },
      { source: "tree-depth", target: "max diameter of components" },
      { source: "tree-depth", target: "path-width" },
      { source: "tree-depth", target: "shrub-depth" },
      { source: "tree-depth", target: "tree bandwidth" },
      { source: "tree-depth", target: "weak ∞-coloring number", type: "equivalent" },
      { source: "tree-independence number", target: "minor-matching hypertree-width" },
      { source: "tree-independence number", target: "o-mim-width" },
      { source: "tree-partition-width", target: "edge-crossing width", type: "equivalent" },
      { source: "tree-partition-width", target: "tree bandwidth" },
      { source: "tree-partition-width", target: "tree-width" },
      { source: "tree-width", target: "bramble number", type: "equivalent" },
      { source: "tree-width", target: "branch-width", type: "equivalent" },
      { source: "tree-width", target: "clique-width" },
      { source: "tree-width", target: "fractional Hadwiger number", type: "equivalent" },
      { source: "tree-width", target: "linkedness", type: "equivalent" },
      { source: "tree-width", target: "separation number", type: "equivalent" },
      { source: "tree-width", target: "stack number" },
      { source: "tree-width", target: "strong ∞-coloring number", type: "equivalent" },
      { source: "tree-width", target: "tangle number", type: "equivalent" },
      { source: "tree-width", target: "track number" },
      { source: "tree-width", target: "tree-independence number" },
      { source: "tree-width", target: "well-linked number", type: "equivalent" },
      { source: "twin-cover", target: "distance to Cluster" },
      { source: "twin-cover", target: "linear rank-width" },
      { source: "twin-cover", target: "modular-width" },
      { source: "twin-width", target: "𝑟-merge-width" },
      { source: "vertex cover number", target: "distance to Co-Cluster" },
      { source: "vertex cover number", target: "distance to disjoint Paths" },
      { source: "vertex cover number", target: "distance to Linear forest" },
      { source: "vertex cover number", target: "maximum matching", type: "equivalent" },
      { source: "vertex cover number", target: "maximum induced matching" },
      { source: "vertex cover number", target: "neighborhood diversity" },
      { source: "vertex cover number", target: "tree-depth" },
      { source: "vertex cover number", target: "twin-cover" },
      { source: "α-edge-crossing width", target: "tree-partition-width" },
      { source: "ℎ-index", target: "acyclic chromatic number" },
      { source: "𝑟-merge-width", target: "𝑟-flip-width" }
    ]
  }
};
