window.GRAPH_CLASS_EXAMPLE = {
  title: "Bounded Parameter Graph Classes",
  subtitle: "If parameter A bounded implies parameter B bounded, then the graph class with bounded A is contained in the graph class with bounded B.",

  // Add graph classes or parameter-defined classes here, sorted alphabetically.
  classes: [
    "\\chi - bounded",
    "Bipartite",
    "Bipartite chain",
    "Bipartite permutation",
    "Block",
    "Bounded ∞-flip-width",
    "Bounded acyclic chromatic number",
    "Bounded arboricity",
    "Bounded average degree",
    "Bounded average distance",
    "Bounded bandwidth",
    "Bounded bisection width",
    "Bounded boolean-width",
    "Bounded boxicity",
    "Bounded bramble number",
    "Bounded branch-depth",
    "Bounded branch-width",
    "Bounded burning number",
    "Bounded 𝑐-closure",
    "Bounded carving-width",
    "Bounded chordality",
    "Bounded chromatic number",
    "Bounded clique cover number",
    "Bounded clique-width",
    "Bounded clique-width \\cap Weakly sparse",
    "Bounded cochromatic number",
    "Bounded component twin-width",
    "Bounded crossing number",
    "Bounded cut-width",
    "Bounded degeneracy",
    "Bounded diameter",
    "Bounded distance to Bipartite",
    "Bounded distance to Block",
    "Bounded distance to Chordal",
    "Bounded distance to Clique",
    "Bounded distance to Cluster",
    "Bounded distance to Co-Cluster",
    "Bounded distance to Cograph",
    "Bounded distance to Disconnected",
    "Bounded distance to Interval",
    "Bounded distance to Linear forest",
    "Bounded distance to Outerplanar",
    "Bounded distance to Perfect",
    "Bounded distance to Planar",
    "Bounded domatic number",
    "Bounded domination number",
    "Bounded edge clique cover number",
    "Bounded edge-crossing width",
    "Bounded edge-cut width",
    "Bounded expansion",
    "Bounded feedback edge set number",
    "Bounded feedback vertex set number",
    "Bounded flip-width",
    "Bounded flip-width \\cap Weakly sparse",
    "Bounded fractional Hadwiger number",
    "Bounded genus",
    "Bounded geometric thickness",
    "Bounded girth",
    "Bounded ℎ-index",
    "Bounded interval number",
    "Bounded linear clique-width",
    "Bounded linear clique-width \\cap Weakly sparse",
    "Bounded linear mim-width",
    "Bounded linear NLC-width",
    "Bounded linear rank-width",
    "Bounded linkedness",
    "Bounded max diameter of components",
    "Bounded max leaf number",
    "Bounded maximum clique",
    "Bounded maximum degree",
    "Bounded maximum independent set",
    "Bounded maximum induced matching",
    "Bounded maximum matching",
    "Bounded merge-width",
    "Bounded mim-width",
    "Bounded minimum degree",
    "Bounded minor-matching hypertree-width",
    "Bounded modular-width",
    "Bounded neighborhood diversity",
    "Bounded NLC-width",
    "Bounded o-mim-width",
    "Bounded path-independence number",
    "Bounded path-width",
    "Bounded path-width \\cap Bounded max-degree",
    "Bounded polynomial expansion",
    "Bounded queue number",
    "Bounded 𝑟-flip-width",
    "Bounded 𝑟-merge-width",
    "Bounded rank-depth",
    "Bounded rank-width",
    "Bounded reduced bandwidth",
    "Bounded reduced component max-leaf",
    "Bounded reduced cut-width",
    "Bounded reduced max-leaf",
    "Bounded separation number",
    "Bounded shrub-depth",
    "Bounded shrub-depth \\cap Weakly sparse",
    "Bounded sim-width",
    "Bounded simultaneous interval number",
    "Bounded slim tree-cut width",
    "Bounded sparse twin-width",
    "Bounded stack number",
    "Bounded stretch-width",
    "Bounded strong ∞-coloring number",
    "Bounded tangle number",
    "Bounded thickness",
    "Bounded thinness",
    "Bounded total twin-width",
    "Bounded track number",
    "Bounded tree bandwidth",
    "Bounded tree-cut width",
    "Bounded tree-depth",
    "Bounded tree-independence number",
    "Bounded tree-partition-width",
    "Bounded tree-width",
    "Bounded twin-cover",
    "Bounded twin-width",
    "Bounded vertex cover number",
    "Bounded weak ∞-coloring number",
    "Bounded well-linked number",
    "Bounded α-edge-crossing width",
    "Cactus",
    "Caterpillar",
    "Chordal",
    "Chordal bipartite",
    "Circle",
    "Circular-arc",
    "Claw-free",
    "Clique",
    "Cluster",
    "Co-cluster",
    "Co-comparability",
    "Cograph",
    "Comparability",
    "Complete bipartite",
    "Complete multipartite",
    "Distance-hereditary",
    "Excluded minor",
    "Excluded topological minor",
    "Forest",
    "Grid",
    "Interval",
    "Line graph",
    "Linear forest",
    "Linearly \\chi - bounded",
    "Low linear rank-width covers",
    "Low rank-width covers",
    "Meyniel",
    "Monadically dependent",
    "Monadically dependent \\cap Weakly sparse",
    "Monadically low VC-density",
    "Monadically stable",
    "Monadically stable \\cap Weakly sparse",
    "Monadically stable bounded clique-width",
    "Monadically stable bounded linear clique-width",
    "Monadically stable bounded merge-width",
    "Monadically stable bounded shrub-depth",
    "Monadically stable bounded twin-width",
    "Nowhere dense",
    "Outerplanar",
    "Parity",
    "Path",
    "Perfect",
    "Permutation",
    "Planar",
    "Polynomially \\chi - bounded",
    "Proper circular-arc",
    "Proper chordal",
    "Proper interval",
    "Ptolemaic",
    "Series-parallel",
    "Split",
    "Split permutation",
    "Star",
    "Strongly chordal",
    "Structurally bounded expansion",
    "Structurally bounded path-width",
    "Structurally bounded sparse twin-width",
    "Structurally bounded tree-depth",
    "Structurally bounded tree-width",
    "Structurally nowhere dense",
    "Threshold",
    "Tree",
    "Trapezoid",
    "Trivially perfect",
    "Wall",
    "Weakly chordal",
    "Weakly sparse"
  ],

  // Primary categories: each class should belong to exactly one of these groups.
  classLabels: [
    {
      id: "basic-graph-classes",
      label: "Basic graph classes",
      classes: [
        "Bipartite",
        "Bipartite chain",
        "Bipartite permutation",
        "Block",
        "Cactus",
        "Caterpillar",
        "Chordal",
        "Chordal bipartite",
        "Circle",
        "Circular-arc",
        "Claw-free",
        "Clique",
        "Cluster",
        "Co-cluster",
        "Co-comparability",
        "Cograph",
        "Comparability",
        "Complete bipartite",
        "Complete multipartite",
        "Distance-hereditary",
        "Forest",
        "Grid",
        "Interval",
        "Line graph",
        "Linear forest",
        "Meyniel",
        "Outerplanar",
        "Parity",
        "Path",
        "Perfect",
        "Permutation",
        "Planar",
        "Proper chordal",
        "Proper circular-arc",
        "Proper interval",
        "Ptolemaic",
        "Series-parallel",
        "Split",
        "Split permutation",
        "Star",
        "Strongly chordal",
        "Threshold",
        "Trapezoid",
        "Tree",
        "Trivially perfect",
        "Wall",
        "Weakly chordal"
      ]
    },
    {
      id: "width-parameter-classes",
      label: "Width parameter classes",
      classes: [
        "Bounded ∞-flip-width",
        "Bounded bandwidth",
        "Bounded bisection width",
        "Bounded boolean-width",
        "Bounded bramble number",
        "Bounded branch-depth",
        "Bounded branch-width",
        "Bounded carving-width",
        "Bounded clique-width",
        "Bounded component twin-width",
        "Bounded cut-width",
        "Bounded edge-crossing width",
        "Bounded edge-cut width",
        "Bounded flip-width",
        "Bounded fractional Hadwiger number",
        "Bounded linear clique-width",
        "Bounded linear mim-width",
        "Bounded linear NLC-width",
        "Bounded linear rank-width",
        "Bounded linkedness",
        "Bounded max leaf number",
        "Bounded merge-width",
        "Bounded mim-width",
        "Bounded minor-matching hypertree-width",
        "Bounded modular-width",
        "Bounded NLC-width",
        "Bounded o-mim-width",
        "Bounded path-independence number",
        "Bounded path-width",
        "Bounded queue number",
        "Bounded 𝑟-flip-width",
        "Bounded 𝑟-merge-width",
        "Bounded rank-depth",
        "Bounded rank-width",
        "Bounded reduced bandwidth",
        "Bounded reduced component max-leaf",
        "Bounded reduced cut-width",
        "Bounded reduced max-leaf",
        "Bounded separation number",
        "Bounded shrub-depth",
        "Bounded sim-width",
        "Bounded slim tree-cut width",
        "Bounded stack number",
        "Bounded stretch-width",
        "Bounded tangle number",
        "Bounded thinness",
        "Bounded total twin-width",
        "Bounded track number",
        "Bounded tree bandwidth",
        "Bounded tree-cut width",
        "Bounded tree-depth",
        "Bounded tree-independence number",
        "Bounded tree-partition-width",
        "Bounded tree-width",
        "Bounded twin-width",
        "Bounded well-linked number",
        "Bounded α-edge-crossing width"
      ]
    },
    {
      id: "graph-parameter-classes",
      label: "Graph parameter classes",
      classes: [
        "Bounded acyclic chromatic number",
        "Bounded arboricity",
        "Bounded average degree",
        "Bounded average distance",
        "Bounded boxicity",
        "Bounded burning number",
        "Bounded 𝑐-closure",
        "Bounded chordality",
        "Bounded chromatic number",
        "Bounded clique cover number",
        "Bounded cochromatic number",
        "Bounded crossing number",
        "Bounded degeneracy",
        "Bounded diameter",
        "Bounded distance to Bipartite",
        "Bounded distance to Block",
        "Bounded distance to Chordal",
        "Bounded distance to Clique",
        "Bounded distance to Cluster",
        "Bounded distance to Co-Cluster",
        "Bounded distance to Cograph",
        "Bounded distance to Disconnected",
        "Bounded distance to Interval",
        "Bounded distance to Linear forest",
        "Bounded distance to Outerplanar",
        "Bounded distance to Perfect",
        "Bounded distance to Planar",
        "Bounded domatic number",
        "Bounded domination number",
        "Bounded edge clique cover number",
        "Bounded feedback edge set number",
        "Bounded feedback vertex set number",
        "Bounded genus",
        "Bounded geometric thickness",
        "Bounded girth",
        "Bounded ℎ-index",
        "Bounded interval number",
        "Bounded max diameter of components",
        "Bounded maximum clique",
        "Bounded maximum degree",
        "Bounded maximum independent set",
        "Bounded maximum induced matching",
        "Bounded maximum matching",
        "Bounded minimum degree",
        "Bounded neighborhood diversity",
        "Bounded simultaneous interval number",
        "Bounded strong ∞-coloring number",
        "Bounded thickness",
        "Bounded twin-cover",
        "Bounded vertex cover number",
        "Bounded weak ∞-coloring number"
      ]
    },
    {
      id: "model-theoretic-classes",
      label: "Model-theoretic classes",
      classes: [
        "Bounded expansion",
        "Bounded polynomial expansion",
        "Bounded sparse twin-width",
        "Excluded minor",
        "Excluded topological minor",
        "Low linear rank-width covers",
        "Low rank-width covers",
        "Monadically dependent",
        "Monadically low VC-density",
        "Monadically stable",
        "Monadically stable bounded clique-width",
        "Monadically stable bounded linear clique-width",
        "Monadically stable bounded merge-width",
        "Monadically stable bounded shrub-depth",
        "Monadically stable bounded twin-width",
        "Nowhere dense",
        "Structurally bounded expansion",
        "Structurally bounded path-width",
        "Structurally bounded sparse twin-width",
        "Structurally bounded tree-depth",
        "Structurally bounded tree-width",
        "Structurally nowhere dense",
        "Weakly sparse"
      ]
    },
    {
      id: "chi-bounded-classes",
      label: "χ-bounded classes",
      classes: [
        "\\chi - bounded",
        "Linearly \\chi - bounded",
        "Polynomially \\chi - bounded"
      ]
    },
    {
      id: "combined-classes",
      label: "Combined classes",
      classes: [
        "Bounded clique-width \\cap Weakly sparse",
        "Bounded flip-width \\cap Weakly sparse",
        "Bounded linear clique-width \\cap Weakly sparse",
        "Bounded path-width \\cap Bounded max-degree",
        "Bounded shrub-depth \\cap Weakly sparse",
        "Monadically dependent \\cap Weakly sparse",
        "Monadically stable \\cap Weakly sparse"
      ]
    }
  ],

  // Optional properties/tags: classes may belong to any number of these groups.
  propertyLabels: [
    {
      id: "fo-ideal",
      label: "FO-ideal",
      classes: [
        "Bounded clique-width",
        "Bounded flip-width",
        "Bounded linear clique-width",
        "Bounded merge-width",
        "Bounded shrub-depth",
        "Bounded twin-width",
        "Monadically dependent"
      ]
    },
    {
      id: "monadically-stable-property",
      label: "Monadically stable",
      classes: [
        "Monadically stable",
        "Monadically stable bounded clique-width",
        "Monadically stable bounded linear clique-width",
        "Monadically stable bounded merge-width",
        "Monadically stable bounded shrub-depth",
        "Monadically stable bounded twin-width"
      ]
    },
    {
      id: "structural-property",
      label: "Structural",
      classes: [
        "Structurally bounded expansion",
        "Structurally bounded path-width",
        "Structurally bounded sparse twin-width",
        "Structurally bounded tree-depth",
        "Structurally bounded tree-width",
        "Structurally nowhere dense"
      ]
    },
    {
      id: "weakly-sparse-property",
      label: "Weakly sparse",
      classes: [
        "Bounded expansion",
        "Bounded path-width",
        "Bounded polynomial expansion",
        "Bounded sparse twin-width",
        "Bounded tree-depth",
        "Bounded tree-width",
        "Excluded minor",
        "Excluded topological minor",
        "Low linear rank-width covers",
        "Low rank-width covers",
        "Nowhere dense",
        "Weakly sparse"
      ]
    },
    {
      id: "hereditary-property",
      label: "Hereditary",
      classes: []
    },
    {
      id: "monotone-property",
      label: "Monotone",
      classes: []
    },
    {
      id: "stable-property",
      label: "Stable",
      classes: []
    }
  ],

  // Add inclusion/equivalence relations here, sorted by source then target.
  relations: [
    { source: "Bipartite", target: "Bounded chromatic number" },
    { source: "Bipartite", target: "Bounded distance to Bipartite" },
    { source: "Bipartite", target: "Comparability" },
    { source: "Bipartite", target: "Perfect" },
    { source: "Bipartite chain", target: "Bipartite" },
    { source: "Bipartite chain", target: "Bipartite permutation" },
    { source: "Bipartite chain", target: "Chordal bipartite" },
    { source: "Bipartite permutation", target: "Bipartite" },
    { source: "Bipartite permutation", target: "Permutation" },
    { source: "Block", target: "Bounded distance to Block" },
    { source: "Block", target: "Chordal" },
    { source: "Block", target: "Ptolemaic" },
    { source: "Bounded ∞-flip-width", target: "Bounded clique-width", type: "equivalent" },
    { source: "Bounded acyclic chromatic number", target: "Bounded boxicity" },
    { source: "Bounded acyclic chromatic number", target: "Bounded degeneracy" },
    { source: "Bounded arboricity", target: "Bounded degeneracy", type: "equivalent" },
    { source: "Bounded average degree", target: "Bounded minimum degree" },
    { source: "Bounded average distance", target: "Bounded girth" },
    { source: "Bounded bandwidth", target: "Bounded bisection width" },
    { source: "Bounded bandwidth", target: "Bounded cut-width" },
    { source: "Bounded bandwidth", target: "Bounded track number" },
    { source: "Bounded bisection width", target: "Bounded distance to Disconnected" },
    { source: "Bounded boolean-width", target: "Bounded clique-width", type: "equivalent" },
    { source: "Bounded boxicity", target: "Bounded chordality" },
    { source: "Bounded bramble number", target: "Bounded tree-width", type: "equivalent" },
    { source: "Bounded branch-depth", target: "Bounded tree-depth", type: "equivalent" },
    { source: "Bounded branch-width", target: "Bounded tree-width", type: "equivalent" },
    { source: "Bounded burning number", target: "Bounded max diameter of components" },
    { source: "Bounded carving-width", target: "Bounded maximum degree" },
    { source: "Bounded carving-width", target: "Bounded slim tree-cut width" },
    { source: "Bounded carving-width", target: "Bounded tree-cut width" },
    { source: "Bounded chromatic number", target: "Bounded chordality" },
    { source: "Bounded chromatic number", target: "Bounded cochromatic number" },
    { source: "Bounded chromatic number", target: "Bounded maximum clique" },
    { source: "Bounded chromatic number", target: "Linearly \\chi - bounded" },
    { source: "Bounded clique cover number", target: "Bounded cochromatic number" },
    { source: "Bounded clique cover number", target: "Bounded maximum independent set" },
    { source: "Bounded clique-width", target: "Bounded ∞-flip-width", type: "equivalent" },
    { source: "Bounded clique-width", target: "Bounded boolean-width", type: "equivalent" },
    { source: "Bounded clique-width", target: "Bounded component twin-width", type: "equivalent" },
    { source: "Bounded clique-width", target: "Bounded mim-width" },
    { source: "Bounded clique-width", target: "Bounded NLC-width", type: "equivalent" },
    { source: "Bounded clique-width", target: "Bounded rank-width", type: "equivalent" },
    { source: "Bounded clique-width", target: "Bounded stretch-width" },
    { source: "Bounded clique-width", target: "Bounded twin-width" },
    { source: "Bounded clique-width \\cap Weakly sparse", target: "Bounded clique-width" },
    { source: "Bounded clique-width \\cap Weakly sparse", target: "Bounded tree-width", type: "equivalent" },
    { source: "Bounded clique-width \\cap Weakly sparse", target: "Weakly sparse" },
    { source: "Bounded component twin-width", target: "Bounded clique-width", type: "equivalent" },
    { source: "Bounded crossing number", target: "Bounded genus" },
    { source: "Bounded crossing number", target: "Excluded minor" },
    { source: "Bounded cut-width", target: "Bounded carving-width" },
    { source: "Bounded cut-width", target: "Bounded path-width" },
    { source: "Bounded cut-width", target: "Bounded path-width \\cap Bounded max-degree", type: "equivalent" },
    { source: "Bounded degeneracy", target: "Bounded arboricity", type: "equivalent" },
    { source: "Bounded degeneracy", target: "Bounded average degree" },
    { source: "Bounded degeneracy", target: "Bounded chromatic number" },
    { source: "Bounded distance to Bipartite", target: "Bounded chromatic number" },
    { source: "Bounded distance to Bipartite", target: "Bounded distance to Perfect" },
    { source: "Bounded distance to Chordal", target: "Bounded chordality" },
    { source: "Bounded distance to Chordal", target: "Bounded distance to Perfect" },
    { source: "Bounded distance to Clique", target: "Bounded clique cover number" },
    { source: "Bounded distance to Clique", target: "Bounded distance to Cluster" },
    { source: "Bounded distance to Clique", target: "Bounded distance to Co-Cluster" },
    { source: "Bounded distance to Clique", target: "Bounded edge clique cover number" },
    { source: "Bounded distance to Cluster", target: "Bounded distance to Block" },
    { source: "Bounded distance to Cluster", target: "Bounded distance to Cograph" },
    { source: "Bounded distance to Cluster", target: "Bounded distance to Interval" },
    { source: "Bounded distance to Co-Cluster", target: "Bounded distance to Cograph" },
    { source: "Bounded distance to Cograph", target: "Bounded chordality" },
    { source: "Bounded distance to Cograph", target: "Bounded clique-width" },
    { source: "Bounded distance to Cograph", target: "Bounded diameter" },
    { source: "Bounded distance to Cograph", target: "Bounded distance to Perfect" },
    { source: "Bounded distance to Cograph", target: "Bounded max diameter of components" },
    { source: "Bounded distance to Interval", target: "Bounded distance to Chordal" },
    { source: "Bounded distance to Linear forest", target: "Bounded distance to Block" },
    { source: "Bounded distance to Linear forest", target: "Bounded distance to Interval" },
    { source: "Bounded distance to Linear forest", target: "Bounded feedback vertex set number" },
    { source: "Bounded distance to Linear forest", target: "Bounded ℎ-index" },
    { source: "Bounded distance to Linear forest", target: "Bounded path-width" },
    { source: "Bounded distance to Outerplanar", target: "Bounded distance to Planar" },
    { source: "Bounded distance to Outerplanar", target: "Bounded tree-width" },
    { source: "Bounded distance to Planar", target: "Bounded acyclic chromatic number" },
    { source: "Bounded distance to Planar", target: "Bounded twin-width" },
    { source: "Bounded domination number", target: "Bounded diameter" },
    { source: "Bounded domination number", target: "Bounded max diameter of components" },
    { source: "Bounded edge clique cover number", target: "Bounded neighborhood diversity" },
    { source: "Bounded edge clique cover number", target: "Bounded simultaneous interval number" },
    { source: "Bounded edge-crossing width", target: "Bounded tree-partition-width", type: "equivalent" },
    { source: "Bounded edge-cut width", target: "Bounded slim tree-cut width" },
    { source: "Bounded expansion", target: "Bounded flip-width \\cap Weakly sparse", type: "equivalent" },
    { source: "Bounded expansion", target: "Nowhere dense" },
    { source: "Bounded expansion", target: "Structurally bounded expansion" },
    { source: "Bounded feedback edge set number", target: "Bounded 𝑐-closure" },
    { source: "Bounded feedback edge set number", target: "Bounded edge-cut width" },
    { source: "Bounded feedback edge set number", target: "Bounded feedback vertex set number" },
    { source: "Bounded feedback edge set number", target: "Bounded genus" },
    { source: "Bounded feedback vertex set number", target: "Bounded distance to Bipartite" },
    { source: "Bounded feedback vertex set number", target: "Bounded distance to Chordal" },
    { source: "Bounded feedback vertex set number", target: "Bounded distance to Outerplanar" },
    { source: "Bounded flip-width", target: "Monadically dependent" },
    { source: "Bounded flip-width \\cap Weakly sparse", target: "Bounded expansion", type: "equivalent" },
    { source: "Bounded flip-width \\cap Weakly sparse", target: "Bounded flip-width" },
    { source: "Bounded flip-width \\cap Weakly sparse", target: "Weakly sparse" },
    { source: "Bounded fractional Hadwiger number", target: "Bounded tree-width", type: "equivalent" },
    { source: "Bounded genus", target: "Bounded stack number" },
    { source: "Bounded genus", target: "Bounded twin-width" },
    { source: "Bounded genus", target: "Excluded minor" },
    { source: "Bounded geometric thickness", target: "Bounded thickness" },
    { source: "Bounded ℎ-index", target: "Bounded acyclic chromatic number" },
    { source: "Bounded interval number", target: "Bounded track number", type: "equivalent" },
    { source: "Bounded linear clique-width", target: "Bounded clique-width" },
    { source: "Bounded linear clique-width", target: "Bounded linear NLC-width", type: "equivalent" },
    { source: "Bounded linear clique-width \\cap Weakly sparse", target: "Bounded linear clique-width" },
    { source: "Bounded linear clique-width \\cap Weakly sparse", target: "Bounded path-width", type: "equivalent" },
    { source: "Bounded linear clique-width \\cap Weakly sparse", target: "Weakly sparse" },
    { source: "Bounded linear mim-width", target: "Bounded mim-width" },
    { source: "Bounded linear NLC-width", target: "Bounded linear clique-width", type: "equivalent" },
    { source: "Bounded linear rank-width", target: "Bounded clique-width" },
    { source: "Bounded linear rank-width", target: "Bounded reduced max-leaf" },
    { source: "Bounded linear rank-width", target: "Bounded total twin-width", type: "equivalent" },
    { source: "Bounded linear rank-width", target: "Low linear rank-width covers" },
    { source: "Bounded linkedness", target: "Bounded tree-width", type: "equivalent" },
    { source: "Bounded max diameter of components", target: "Bounded average distance" },
    { source: "Bounded max leaf number", target: "Bounded bandwidth" },
    { source: "Bounded max leaf number", target: "Bounded distance to Linear forest" },
    { source: "Bounded max leaf number", target: "Bounded feedback edge set number" },
    { source: "Bounded maximum degree", target: "Bounded chromatic number" },
    { source: "Bounded maximum degree", target: "Bounded degeneracy" },
    { source: "Bounded maximum degree", target: "Bounded 𝑐-closure" },
    { source: "Bounded maximum degree", target: "Bounded ℎ-index" },
    { source: "Bounded maximum independent set", target: "Bounded domination number" },
    { source: "Bounded maximum independent set", target: "Bounded maximum induced matching" },
    { source: "Bounded maximum induced matching", target: "Bounded diameter" },
    { source: "Bounded maximum matching", target: "Bounded vertex cover number", type: "equivalent" },
    { source: "Bounded mim-width", target: "Bounded o-mim-width" },
    { source: "Bounded minimum degree", target: "Bounded distance to Disconnected" },
    { source: "Bounded minimum degree", target: "Bounded domatic number" },
    { source: "Bounded minor-matching hypertree-width", target: "Bounded sim-width" },
    { source: "Bounded modular-width", target: "Bounded clique-width" },
    { source: "Bounded modular-width", target: "Bounded max diameter of components" },
    { source: "Bounded neighborhood diversity", target: "Bounded modular-width" },
    { source: "Bounded NLC-width", target: "Bounded clique-width", type: "equivalent" },
    { source: "Bounded o-mim-width", target: "Bounded sim-width" },
    { source: "Bounded path-independence number", target: "Bounded tree-independence number" },
    { source: "Bounded path-width", target: "Bounded linear clique-width" },
    { source: "Bounded path-width", target: "Bounded linear clique-width \\cap Weakly sparse", type: "equivalent" },
    { source: "Bounded path-width", target: "Bounded simultaneous interval number" },
    { source: "Bounded path-width", target: "Bounded tree-width" },
    { source: "Bounded path-width", target: "Structurally bounded path-width" },
    { source: "Bounded path-width \\cap Bounded max-degree", target: "Bounded cut-width", type: "equivalent" },
    { source: "Bounded polynomial expansion", target: "Bounded expansion" },
    { source: "Bounded queue number", target: "Bounded track number", type: "equivalent" },
    { source: "Bounded 𝑟-merge-width", target: "Bounded 𝑟-flip-width" },
    { source: "Bounded rank-depth", target: "Bounded shrub-depth", type: "equivalent" },
    { source: "Bounded rank-width", target: "Bounded clique-width", type: "equivalent" },
    { source: "Bounded rank-width", target: "Bounded reduced component max-leaf" },
    { source: "Bounded rank-width", target: "Low rank-width covers" },
    { source: "Bounded rank-width", target: "Monadically low VC-density" },
    { source: "Bounded reduced bandwidth", target: "Bounded reduced cut-width" },
    { source: "Bounded reduced component max-leaf", target: "Bounded reduced bandwidth" },
    { source: "Bounded reduced cut-width", target: "Bounded twin-width" },
    { source: "Bounded reduced max-leaf", target: "Bounded reduced component max-leaf" },
    { source: "Bounded separation number", target: "Bounded tree-width", type: "equivalent" },
    { source: "Bounded shrub-depth", target: "Bounded linear clique-width" },
    { source: "Bounded shrub-depth", target: "Bounded rank-depth", type: "equivalent" },
    { source: "Bounded shrub-depth \\cap Weakly sparse", target: "Bounded shrub-depth" },
    { source: "Bounded shrub-depth \\cap Weakly sparse", target: "Bounded tree-depth", type: "equivalent" },
    { source: "Bounded shrub-depth \\cap Weakly sparse", target: "Weakly sparse" },
    { source: "Bounded simultaneous interval number", target: "Bounded path-independence number" },
    { source: "Bounded simultaneous interval number", target: "Bounded thinness" },
    { source: "Bounded simultaneous interval number", target: "Bounded track number" },
    { source: "Bounded slim tree-cut width", target: "Bounded tree-cut width" },
    { source: "Bounded slim tree-cut width", target: "Bounded α-edge-crossing width" },
    { source: "Bounded sparse twin-width", target: "Bounded expansion" },
    { source: "Bounded sparse twin-width", target: "Structurally bounded sparse twin-width" },
    { source: "Bounded stack number", target: "Bounded acyclic chromatic number" },
    { source: "Bounded stack number", target: "Bounded geometric thickness" },
    { source: "Bounded stretch-width", target: "Bounded reduced bandwidth" },
    { source: "Bounded strong ∞-coloring number", target: "Bounded tree-width", type: "equivalent" },
    { source: "Bounded tangle number", target: "Bounded tree-width", type: "equivalent" },
    { source: "Bounded thickness", target: "Bounded average degree" },
    { source: "Bounded thinness", target: "Bounded boxicity" },
    { source: "Bounded thinness", target: "Bounded linear mim-width" },
    { source: "Bounded total twin-width", target: "Bounded linear rank-width", type: "equivalent" },
    { source: "Bounded track number", target: "Bounded acyclic chromatic number" },
    { source: "Bounded track number", target: "Bounded geometric thickness" },
    { source: "Bounded track number", target: "Bounded interval number", type: "equivalent" },
    { source: "Bounded track number", target: "Bounded queue number", type: "equivalent" },
    { source: "Bounded tree bandwidth", target: "Bounded tree-width" },
    { source: "Bounded tree-cut width", target: "Bounded tree-partition-width" },
    { source: "Bounded tree-depth", target: "Bounded branch-depth", type: "equivalent" },
    { source: "Bounded tree-depth", target: "Bounded diameter" },
    { source: "Bounded tree-depth", target: "Bounded max diameter of components" },
    { source: "Bounded tree-depth", target: "Bounded path-width" },
    { source: "Bounded tree-depth", target: "Bounded shrub-depth" },
    { source: "Bounded tree-depth", target: "Bounded shrub-depth \\cap Weakly sparse", type: "equivalent" },
    { source: "Bounded tree-depth", target: "Bounded tree bandwidth" },
    { source: "Bounded tree-depth", target: "Bounded weak ∞-coloring number", type: "equivalent" },
    { source: "Bounded tree-depth", target: "Structurally bounded tree-depth" },
    { source: "Bounded tree-independence number", target: "Bounded minor-matching hypertree-width" },
    { source: "Bounded tree-independence number", target: "Bounded o-mim-width" },
    { source: "Bounded tree-partition-width", target: "Bounded edge-crossing width", type: "equivalent" },
    { source: "Bounded tree-partition-width", target: "Bounded tree bandwidth" },
    { source: "Bounded tree-partition-width", target: "Bounded tree-width" },
    { source: "Bounded tree-width", target: "Bounded bramble number", type: "equivalent" },
    { source: "Bounded tree-width", target: "Bounded branch-width", type: "equivalent" },
    { source: "Bounded tree-width", target: "Bounded clique-width" },
    { source: "Bounded tree-width", target: "Bounded clique-width \\cap Weakly sparse", type: "equivalent" },
    { source: "Bounded tree-width", target: "Bounded fractional Hadwiger number", type: "equivalent" },
    { source: "Bounded tree-width", target: "Bounded linkedness", type: "equivalent" },
    { source: "Bounded tree-width", target: "Bounded separation number", type: "equivalent" },
    { source: "Bounded tree-width", target: "Bounded stack number" },
    { source: "Bounded tree-width", target: "Bounded strong ∞-coloring number", type: "equivalent" },
    { source: "Bounded tree-width", target: "Bounded tangle number", type: "equivalent" },
    { source: "Bounded tree-width", target: "Bounded track number" },
    { source: "Bounded tree-width", target: "Bounded tree-independence number" },
    { source: "Bounded tree-width", target: "Bounded well-linked number", type: "equivalent" },
    { source: "Bounded tree-width", target: "Excluded minor" },
    { source: "Bounded tree-width", target: "Structurally bounded tree-width" },
    { source: "Bounded twin-cover", target: "Bounded distance to Cluster" },
    { source: "Bounded twin-cover", target: "Bounded linear rank-width" },
    { source: "Bounded twin-cover", target: "Bounded modular-width" },
    { source: "Bounded twin-width", target: "Bounded merge-width" },
    { source: "Bounded twin-width", target: "Bounded 𝑟-merge-width" },
    { source: "Bounded vertex cover number", target: "Bounded distance to Co-Cluster" },
    { source: "Bounded vertex cover number", target: "Bounded distance to Linear forest" },
    { source: "Bounded vertex cover number", target: "Bounded maximum induced matching" },
    { source: "Bounded vertex cover number", target: "Bounded maximum matching", type: "equivalent" },
    { source: "Bounded vertex cover number", target: "Bounded neighborhood diversity" },
    { source: "Bounded vertex cover number", target: "Bounded tree-depth" },
    { source: "Bounded vertex cover number", target: "Bounded twin-cover" },
    { source: "Bounded weak ∞-coloring number", target: "Bounded tree-depth", type: "equivalent" },
    { source: "Bounded well-linked number", target: "Bounded tree-width", type: "equivalent" },
    { source: "Bounded α-edge-crossing width", target: "Bounded tree-partition-width" },
    { source: "Cactus", target: "Outerplanar" },
    { source: "Caterpillar", target: "Co-comparability" },
    { source: "Caterpillar", target: "Interval" },
    { source: "Caterpillar", target: "Tree" },
    { source: "Chordal", target: "Bounded chordality" },
    { source: "Chordal", target: "Bounded distance to Chordal" },
    { source: "Chordal", target: "Perfect" },
    { source: "Chordal", target: "Weakly chordal" },
    { source: "Chordal bipartite", target: "Bipartite" },
    { source: "Chordal bipartite", target: "Perfect" },
    { source: "Chordal bipartite", target: "Weakly chordal" },
    { source: "Clique", target: "Bounded distance to Clique" },
    { source: "Clique", target: "Cluster" },
    { source: "Clique", target: "Co-cluster" },
    { source: "Clique", target: "Interval" },
    { source: "Clique", target: "Proper interval" },
    { source: "Clique", target: "Threshold" },
    { source: "Cluster", target: "Block" },
    { source: "Cluster", target: "Bounded distance to Cluster" },
    { source: "Cluster", target: "Cograph" },
    { source: "Cluster", target: "Interval" },
    { source: "Cluster", target: "Proper interval" },
    { source: "Co-cluster", target: "Bounded distance to Co-Cluster" },
    { source: "Co-cluster", target: "Cograph" },
    { source: "Co-comparability", target: "Perfect" },
    { source: "Cograph", target: "Bounded clique-width" },
    { source: "Cograph", target: "Bounded distance to Cograph" },
    { source: "Cograph", target: "Distance-hereditary" },
    { source: "Cograph", target: "Perfect" },
    { source: "Comparability", target: "Perfect" },
    { source: "Complete bipartite", target: "Bipartite" },
    { source: "Complete bipartite", target: "Bipartite chain" },
    { source: "Complete bipartite", target: "Complete multipartite" },
    { source: "Complete multipartite", target: "Co-cluster", type: "equivalent" },
    { source: "Distance-hereditary", target: "Bounded clique-width" },
    { source: "Distance-hereditary", target: "Bounded rank-width" },
    { source: "Distance-hereditary", target: "Circle" },
    { source: "Distance-hereditary", target: "Meyniel" },
    { source: "Distance-hereditary", target: "Parity" },
    { source: "Distance-hereditary", target: "Perfect" },
    { source: "Excluded minor", target: "Bounded polynomial expansion" },
    { source: "Excluded minor", target: "Bounded sparse twin-width" },
    { source: "Excluded minor", target: "Excluded topological minor" },
    { source: "Excluded topological minor", target: "Bounded expansion" },
    { source: "Forest", target: "Bipartite" },
    { source: "Forest", target: "Chordal" },
    { source: "Forest", target: "Outerplanar" },
    { source: "Grid", target: "Bipartite" },
    { source: "Grid", target: "Bounded maximum degree" },
    { source: "Grid", target: "Planar" },
    { source: "Interval", target: "Bounded distance to Interval" },
    { source: "Interval", target: "Chordal" },
    { source: "Interval", target: "Circular-arc" },
    { source: "Interval", target: "Co-comparability" },
    { source: "Interval", target: "Trapezoid" },
    { source: "Line graph", target: "Claw-free" },
    { source: "Linear forest", target: "Bounded distance to Linear forest" },
    { source: "Linear forest", target: "Bounded maximum degree" },
    { source: "Linear forest", target: "Forest" },
    { source: "Linear forest", target: "Proper interval" },
    { source: "Linearly \\chi - bounded", target: "Polynomially \\chi - bounded" },
    { source: "Low linear rank-width covers", target: "Linearly \\chi - bounded" },
    { source: "Low linear rank-width covers", target: "Low rank-width covers" },
    { source: "Low rank-width covers", target: "Polynomially \\chi - bounded" },
    { source: "Meyniel", target: "Perfect" },
    { source: "Monadically dependent \\cap Weakly sparse", target: "Monadically dependent" },
    { source: "Monadically dependent \\cap Weakly sparse", target: "Nowhere dense", type: "equivalent" },
    { source: "Monadically dependent \\cap Weakly sparse", target: "Weakly sparse" },
    { source: "Monadically low VC-density", target: "Monadically dependent" },
    { source: "Monadically stable", target: "Monadically dependent" },
    { source: "Monadically stable \\cap Weakly sparse", target: "Monadically stable" },
    { source: "Monadically stable \\cap Weakly sparse", target: "Nowhere dense", type: "equivalent" },
    { source: "Monadically stable \\cap Weakly sparse", target: "Weakly sparse" },
    { source: "Monadically stable bounded clique-width", target: "Bounded clique-width" },
    { source: "Monadically stable bounded clique-width", target: "Monadically stable bounded twin-width" },
    { source: "Monadically stable bounded linear clique-width", target: "Bounded linear clique-width" },
    { source: "Monadically stable bounded linear clique-width", target: "Monadically stable bounded clique-width" },
    { source: "Monadically stable bounded merge-width", target: "Bounded merge-width" },
    { source: "Monadically stable bounded merge-width", target: "Monadically stable" },
    { source: "Monadically stable bounded shrub-depth", target: "Bounded shrub-depth" },
    { source: "Monadically stable bounded shrub-depth", target: "Monadically stable bounded linear clique-width" },
    { source: "Monadically stable bounded twin-width", target: "Bounded twin-width" },
    { source: "Monadically stable bounded twin-width", target: "Monadically stable bounded merge-width" },
    { source: "Nowhere dense", target: "Monadically dependent \\cap Weakly sparse", type: "equivalent" },
    { source: "Nowhere dense", target: "Monadically stable \\cap Weakly sparse", type: "equivalent" },
    { source: "Nowhere dense", target: "Structurally nowhere dense" },
    { source: "Nowhere dense", target: "Weakly sparse" },
    { source: "Outerplanar", target: "Bounded distance to Outerplanar" },
    { source: "Outerplanar", target: "Circle" },
    { source: "Outerplanar", target: "Series-parallel" },
    { source: "Parity", target: "Perfect" },
    { source: "Path", target: "Bounded maximum degree" },
    { source: "Path", target: "Caterpillar" },
    { source: "Path", target: "Grid" },
    { source: "Path", target: "Linear forest" },
    { source: "Path", target: "Tree" },
    { source: "Perfect", target: "Bounded distance to Perfect" },
    { source: "Perfect", target: "Linearly \\chi - bounded" },
    { source: "Permutation", target: "Co-comparability" },
    { source: "Permutation", target: "Comparability" },
    { source: "Permutation", target: "Circle" },
    { source: "Permutation", target: "Trapezoid" },
    { source: "Planar", target: "Bounded crossing number" },
    { source: "Planar", target: "Bounded distance to Planar" },
    { source: "Planar", target: "Bounded genus" },
    { source: "Planar", target: "Excluded minor" },
    { source: "Polynomially \\chi - bounded", target: "\\chi - bounded" },
    { source: "Proper circular-arc", target: "Circular-arc" },
    { source: "Proper circular-arc", target: "Claw-free" },
    { source: "Proper chordal", target: "Chordal" },
    { source: "Proper chordal", target: "Strongly chordal" },
    { source: "Proper interval", target: "Chordal" },
    { source: "Proper interval", target: "Interval" },
    { source: "Proper interval", target: "Proper chordal" },
    { source: "Proper interval", target: "Proper circular-arc" },
    { source: "Ptolemaic", target: "Chordal" },
    { source: "Ptolemaic", target: "Distance-hereditary" },
    { source: "Series-parallel", target: "Bounded chromatic number" },
    { source: "Series-parallel", target: "Bounded tree-width" },
    { source: "Series-parallel", target: "Planar" },
    { source: "Split", target: "Chordal" },
    { source: "Split", target: "Perfect" },
    { source: "Split permutation", target: "Permutation" },
    { source: "Split permutation", target: "Split" },
    { source: "Star", target: "Bipartite chain" },
    { source: "Star", target: "Caterpillar" },
    { source: "Star", target: "Complete bipartite" },
    { source: "Star", target: "Split" },
    { source: "Star", target: "Threshold" },
    { source: "Strongly chordal", target: "Chordal" },
    { source: "Structurally bounded expansion", target: "Low linear rank-width covers" },
    { source: "Structurally bounded expansion", target: "Monadically stable bounded merge-width" },
    { source: "Structurally bounded expansion", target: "Structurally nowhere dense" },
    { source: "Structurally bounded path-width", target: "Monadically stable bounded linear clique-width" },
    { source: "Structurally bounded path-width", target: "Structurally bounded tree-width" },
    { source: "Structurally bounded sparse twin-width", target: "Monadically stable bounded twin-width" },
    { source: "Structurally bounded sparse twin-width", target: "Structurally bounded expansion" },
    { source: "Structurally bounded tree-depth", target: "Monadically stable bounded shrub-depth" },
    { source: "Structurally bounded tree-depth", target: "Structurally bounded path-width" },
    { source: "Structurally bounded tree-width", target: "Monadically stable bounded clique-width" },
    { source: "Structurally bounded tree-width", target: "Structurally bounded sparse twin-width" },
    { source: "Structurally nowhere dense", target: "Monadically low VC-density" },
    { source: "Structurally nowhere dense", target: "Monadically stable" },
    { source: "Threshold", target: "Cograph" },
    { source: "Threshold", target: "Permutation" },
    { source: "Threshold", target: "Split" },
    { source: "Threshold", target: "Split permutation" },
    { source: "Threshold", target: "Trivially perfect" },
    { source: "Tree", target: "Cactus" },
    { source: "Tree", target: "Block" },
    { source: "Tree", target: "Forest" },
    { source: "Trivially perfect", target: "Cograph" },
    { source: "Trivially perfect", target: "Strongly chordal" },
    { source: "Wall", target: "Bounded crossing number" },
    { source: "Wall", target: "Bounded maximum degree" },
    { source: "Wall", target: "Planar" },
    { source: "Weakly chordal", target: "Perfect" }
  ]
};
